version: '3.7'
services: 
  api: 
    build:
      context: . 
      dockerfile: Dockerfile
    environment: 
      PORT: 3000
      DATABASE_URL: ${DATABASE_URL}
      TOKEN_SECRET: ${TOKEN_SECRET}
    ports: 
      - '3000:3000'
    command: ['npm', 'start']
    depends_on: 
      - mongo
  mongo:
    image: mongo
    ports: 
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      

    
    
     
